Completed Rewrite
Carson-Bay/DMBot pull request #82
Opened 2021-03-07 18:50 UTC by TheArchitect4855

2021-03-07 20:14 UTC, Carson-Bay requested changes

2021-03-07 20:14 UTC, Carson-Bay commented on commands.py
> +async def roll(args, context, state):
If this file is the sub-command handler then the commands like roll and others below should be moved to their own files. Don't be scared of having a bunch of small files.

2021-03-07 20:14 UTC, Carson-Bay commented on commands_mod/character.py
> +async def create(args, context, state):
Could you explain the change of sending in "state" (whatever that is) instead of the client

2021-03-07 20:14 UTC, Carson-Bay commented on commands_mod/character.py
> +	channel = context.channel
This is just a point of preference of mine to shorten names classes that are called often aka "ctx" instead of "context"

It's the more pythonic way of doing things and in the end, will make for cleaner code IMO.

2021-03-07 20:14 UTC, Carson-Bay commented on embeds.py
> +COLOURS = {
Convert to discord colour objects like in Legacy

2021-03-07 20:14 UTC, Carson-Bay commented on main.py
> +		return # Don't respond to messages sent by ourselves
```suggestion
		return # Don't respond to messages sent by the bot itself
```

2021-03-07 20:14 UTC, Carson-Bay commented on main.py
> +def main():
Not often you will make a "main" function in python and will just put this code straight in the "if __name__....", Curious if there was a reason behind this

2021-03-07 20:14 UTC, Carson-Bay commented on requirements.txt
> -discord~=1.0.1
Why did we delete this file?? Super useful to keep a requirements file and will most likely be needed when hosting the bot.

2021-03-07 20:14 UTC, Carson-Bay commented on runtime.txt
> -python-3.8.6
I would also want to keep this file just in case we still want to run tests on heroku

2021-03-07 20:14 UTC, Carson-Bay commented on Procfile
> -worker: python Bot/main.py
Keep this file so we can do tests on the Heroku (change to proper file path if keeping)

2021-03-07 20:14 UTC, Carson-Bay commented on Bot/monstersParser.py
> -# Monster data taken from http://donjon.bin.sh/5e/monsters/
Any reason to remove this?

2021-03-07 20:19 UTC, TheArchitect4855 commented on ARCHITECTURE.md
> +All top-level commands (i.e. echo, character, changeprefix, etc.). Sub-commands (e.g. character ...) should be
The bot state is just all of the "global" bot data. I think it's better to have a structure with getters and setters as opposed to what we had before (a bunch of global dictionaries). 

Currently, the state class only contains the discord.py client and all of the prefixes, but in the future this will contain characters, sessions, and all of that stuff as well.

2021-03-07 20:20 UTC, TheArchitect4855 commented on ARCHITECTURE.md
> +Manages bot state.
The bot state is just all of the "global" bot data. I think it's better to have a structure with getters and setters as opposed to what we had before (a bunch of global dictionaries). 

Currently, the state class only contains the discord.py client and all of the prefixes, but in the future this will contain characters, sessions, and all of that stuff as well.

2021-03-07 20:21 UTC, TheArchitect4855 commented on args.py
> +if __name__ == "__main__":
That would probably be a good idea. I wasn't sure how unit testing worked in Python so I just did this.

I can remove that test function if you want.

2021-03-07 20:22 UTC, TheArchitect4855 commented on commands.py
> +from commands_mod import lookup as lookup_commands
The "as" keyword in Python is just for creating aliases. In this case, it's used to prevent name conflicts.

2021-03-07 20:23 UTC, TheArchitect4855 commented on commands.py
> +import random
Yeah, this is just the top-level commands.

What would a more descriptive name be?

2021-03-07 20:23 UTC, TheArchitect4855 commented on main.py
> +def main():
Putting tons of code in an if statement is generally bad practice; it's better to separate it into a function.

2021-03-07 20:24 UTC, TheArchitect4855 commented on requirements.txt
> -discord~=1.0.1
I didn't need it; but I can recreate one easily enough.

2021-03-07 20:25 UTC, TheArchitect4855 commented on Bot/monstersParser.py
> -# Monster data taken from http://donjon.bin.sh/5e/monsters/
I didn't look through all the old code; I just wiped it. I'll probably pull this from the old repo when we get to the monster lookup stuff.

2021-03-08 01:08 UTC, Carson-Bay commented on args.py
> +if __name__ == "__main__":
I say remove it now but make an issue to add Pytest on all our functions

2021-03-08 01:09 UTC, Carson-Bay commented on commands.py
> +from commands_mod import lookup as lookup_commands
Fair enough

2021-03-08 01:10 UTC, Carson-Bay commented on main.py
> +def main():
I guess was more of just a preference thing of what I'm used to with python

2021-03-08 01:11 UTC, Carson-Bay commented on ARCHITECTURE.md
> +Manages bot state.
oooh okay, that makes sense. In my mind "state" didn't encompass all of the other data which is why I was confused.

2021-03-08 01:12 UTC, Carson-Bay commented on commands.py
> +import random
Command handlers or something along that line. Having a commands file and a commands folder could get sketchy

2021-03-08 01:15 UTC, Carson-Bay commented on ARCHITECTURE.md
> +Manages bot state.
Maybe just add that explanation to the architecture file as atm it seems like it just holds the bots state like if it's on or not.

2021-03-10 00:09 UTC, TheArchitect4855 commented on ARCHITECTURE.md
> +Manages bot state.
Roger roger. All done.

2021-03-10 00:12 UTC, TheArchitect4855 commented on commands.py
> +import random
Roger roger

2021-03-10 00:23 UTC, TheArchitect4855 commented on commands_mod/character.py
> +	channel = context.channel
Honestly I prefer context. If you really want it to be ctx, I can change it, but I don't think it's a huge deal.

2021-03-10 00:37 UTC, Carson-Bay requested changes

2021-03-10 00:37 UTC, Carson-Bay commented on main.py
> +from commands import roll
```suggestion
from commands import roll, change_prefix
```

2021-03-10 00:41 UTC, merged